[#ftl]
[#include "../formMacros.ftl"]
[@container "text-center"]
    [@hiddenInput "add-persoana-to-project-idProiect" "idProiect"/]
    [@input "add-persoana-to-project-fullName" "fullName" "TYPE_PERSON_NAME" "TYPE_PERSON_NAME" "" "10 col-md-offset-1"/]
[/@container]