INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (1, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'United States');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (2, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Canada');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (3, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Afghanistan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (4, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Albania');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (5, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Algeria');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (6, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'American Samoa');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (7, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Andorra');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (8, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Angola');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (9, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Anguilla');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (10, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Antarctica');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (11, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Antigua and/or Barbuda');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (12, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Argentina');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (13, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Armenia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (14, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Aruba');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (15, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Australia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (16, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Austria');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (17, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Azerbaijan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (18, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bahamas');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (19, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bahrain');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (20, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bangladesh');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (21, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Barbados');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (22, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Belarus');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (23, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Belgium');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (24, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Belize');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (25, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Benin');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (26, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bermuda');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (27, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bhutan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (28, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bolivia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (29, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bosnia and Herzegovina');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (30, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Botswana');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (31, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bouvet Island');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (32, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Brazil');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (33, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'British Indian Ocean Territory');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (34, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Brunei Darussalam');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (35, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Bulgaria');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (36, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Burkina Faso');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (37, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Burundi');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (38, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cambodia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (39, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cameroon');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (40, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cape Verde');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (41, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cayman Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (42, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Central African Republic');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (43, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Chad');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (44, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Chile');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (45, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'China');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (46, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Christmas Island');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (47, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cocos (Keeling) Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (48, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Colombia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (49, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Comoros');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (50, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Congo');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (51, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cook Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (52, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Costa Rica');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (53, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Croatia (Hrvatska)');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (54, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cuba');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (55, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Cyprus');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (56, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Czech Republic');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (57, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Denmark');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (58, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Djibouti');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (59, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Dominica');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (60, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Dominican Republic');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (61, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'East Timor');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (62, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ecuador');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (63, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Egypt');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (64, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'El Salvador');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (65, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Equatorial Guinea');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (66, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Eritrea');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (67, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Estonia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (68, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ethiopia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (69, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Falkland Islands (Malvinas)');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (70, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Faroe Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (71, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Fiji');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (72, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Finland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (73, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'France');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (74, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'France, Metropolitan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (75, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'French Guiana');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (76, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'French Polynesia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (77, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'French Southern Territories');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (78, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Gabon');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (79, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Gambia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (80, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Georgia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (81, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Germany');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (82, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ghana');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (83, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Gibraltar');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (84, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guernsey');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (85, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Greece');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (86, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Greenland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (87, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Grenada');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (88, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guadeloupe');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (89, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guam');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (90, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guatemala');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (91, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guinea');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (92, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guinea-Bissau');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (93, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Guyana');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (94, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Haiti');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (95, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Heard and Mc Donald Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (96, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Honduras');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (97, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Hong Kong');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (98, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Hungary');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (99, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Iceland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (100, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'India');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (101, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Isle of Man');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (102, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Indonesia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (103, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Iran (Islamic Republic of)');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (104, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Iraq');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (105, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ireland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (106, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Israel');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (107, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Italy');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (108, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ivory Coast');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (109, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Jersey');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (110, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Jamaica');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (111, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Japan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (112, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Jordan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (113, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kazakhstan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (114, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kenya');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (115, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kiribati');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (116, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Korea, Democratic People''s Republic of');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (117, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Korea, Republic of');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (118, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kosovo');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (119, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kuwait');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (120, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Kyrgyzstan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (121, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Lao People''s Democratic Republic');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (122, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Latvia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (123, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Lebanon');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (124, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Lesotho');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (125, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Liberia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (126, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Libyan Arab Jamahiriya');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (127, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Liechtenstein');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (128, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Lithuania');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (129, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Luxembourg');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (130, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Macau');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (131, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Macedonia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (132, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Madagascar');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (133, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Malawi');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (134, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Malaysia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (135, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Maldives');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (136, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mali');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (137, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Malta');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (138, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Marshall Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (139, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Martinique');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (140, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mauritania');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (141, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mauritius');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (142, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mayotte');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (143, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mexico');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (144, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Micronesia, Federated States of');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (145, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Moldova, Republic of');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (146, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Monaco');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (147, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mongolia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (148, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Montenegro');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (149, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Montserrat');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (150, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Morocco');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (151, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Mozambique');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (152, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Myanmar');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (153, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Namibia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (154, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Nauru');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (155, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Nepal');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (156, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Netherlands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (157, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Netherlands Antilles');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (158, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'New Caledonia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (159, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'New Zealand');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (160, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Nicaragua');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (161, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Niger');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (162, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Nigeria');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (163, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Niue');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (164, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Norfolk Island');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (165, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Northern Mariana Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (166, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Norway');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (167, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Oman');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (168, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Pakistan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (169, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Palau');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (170, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Palestine');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (171, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Panama');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (172, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Papua New Guinea');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (173, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Paraguay');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (174, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Peru');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (175, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Philippines');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (176, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Pitcairn');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (177, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Poland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (178, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Portugal');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (179, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Puerto Rico');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (180, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Qatar');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (181, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Reunion');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (182, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Romania');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (183, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Russian Federation');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (184, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Rwanda');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (185, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Saint Kitts and Nevis');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (186, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Saint Lucia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (187, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Saint Vincent and the Grenadines');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (188, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Samoa');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (189, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'San Marino');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (190, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Sao Tome and Principe');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (191, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Saudi Arabia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (192, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Senegal');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (193, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Serbia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (194, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Seychelles');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (195, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Sierra Leone');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (196, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Singapore');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (197, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Slovakia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (198, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Slovenia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (199, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Solomon Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (200, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Somalia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (201, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'South Africa');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (202, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'South Georgia South Sandwich Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (203, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Spain');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (204, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Sri Lanka');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (205, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'St. Helena');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (206, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'St. Pierre and Miquelon');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (207, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Sudan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (208, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Suriname');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (209, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Svalbard and Jan Mayen Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (210, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Swaziland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (211, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Sweden');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (212, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Switzerland');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (213, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Syrian Arab Republic');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (214, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Taiwan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (215, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tajikistan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (216, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tanzania, United Republic of');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (217, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Thailand');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (218, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Togo');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (219, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tokelau');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (220, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tonga');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (221, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Trinidad and Tobago');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (222, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tunisia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (223, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Turkey');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (224, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Turkmenistan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (225, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Turks and Caicos Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (226, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Tuvalu');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (227, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Uganda');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (228, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Ukraine');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (229, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'United Arab Emirates');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (230, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'United Kingdom');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (231, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'United States minor outlying islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (232, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Uruguay');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (233, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Uzbekistan');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (234, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Vanuatu');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (235, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Vatican City State');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (236, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Venezuela');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (237, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Vietnam');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (238, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Virgin Islands (British)');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (239, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Virgin Islands (U.S.)');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume)
VALUES (240, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Wallis and Futuna Islands');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (241, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Western Sahara');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (242, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Yemen');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (243, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Yugoslavia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (244, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Zaire');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (245, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Zambia');
INSERT INTO raindrop.lista_tari (id_tara, creat_de, creat_la, modificat_de, modificat_la, nume) VALUES (246, 'admin', '2015-10-24 11:34:06', NULL, NULL, 'Zimbabwe');
